# Generated by Django 3.2.9 on 2021-12-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default=1, max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Status'],
            },
        ),
        migrations.CreateModel(
            name='ClosedChange',
            fields=[
            ],
            options={
                'verbose_name': 'Closed Changes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.change',),
        ),
    ]
